services:
  nest-backend:
    container_name: nest-app
    image: nest-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5000:5000
    environment:
      - DB_TYPE=postgres
      - DB_SCHEMA=public
      - PG_HOST=postgres
      - PG_USER=younes_kebli
      - PG_PASSWORD=123456789
      - PG_DB=e_book
      - PG_PORT=5432
    networks:
      backend_network:
        ipv4_address: 172.28.0.6 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres
  postgres:
    container_name: postgres-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=younes_kebli
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=e_book
    networks:
      backend_network:
        ipv4_address: 172.28.0.5
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      backend_network:
        ipv4_address: 172.28.0.4
    ports:
      - '5050:80'
    depends_on:
      - postgres
networks:
  backend_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
volumes:
  postgres_data: {}