version: '3.8'
services:
  dev-db:
    image: postgres:latest
    restart: always
    environment:
        POSTGRES_USER: younes
        POSTGRES_PASSWORD: 123456789
        POSTGRES_DB: e_book
    container_name: postgres
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
